name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: check gift dif
        run: |
          ls -la
          git status
          git fetch --all
          git checkout staging
          git status
          git branch -a
          echo -------------------------diff----------------------
          git diff --name-only main
           echo -------------------------diff----------------------